begin;
alter table public.places add column if not exists neighborhood text not null default 'West Village';
alter table public.places add column if not exists latitude double precision;
alter table public.places add column if not exists longitude double precision;
alter table public.places add column if not exists coordinate_source_url text;
alter table public.places drop constraint if exists places_kind_check;
alter table public.places add constraint places_kind_check check (kind in ('coffee','park','library','garden','bookshop','landmark','gallery'));
-- Original catalogue rows and generations remain intact.
update public.places set neighborhood='West Village',latitude=40.7349281,longitude=-74.0022788,coordinate_source_url='https://www.openstreetmap.org/node/4909655521' where id='partners-village';
update public.places set neighborhood='West Village',latitude=40.738363,longitude=-74.00023,coordinate_source_url='https://www.openstreetmap.org/way/250490712' where id='birch-village';
update public.places set neighborhood='West Village',latitude=40.734588,longitude=-73.999192,coordinate_source_url='https://www.openstreetmap.org/way/249664014' where id='jefferson-library';
update public.places set neighborhood='West Village',latitude=40.7344521,longitude=-73.9994809,coordinate_source_url='https://www.openstreetmap.org/way/239988120' where id='jefferson-garden';
update public.places set neighborhood='West Village',latitude=40.7312348,longitude=-73.9971025,coordinate_source_url='https://www.openstreetmap.org/way/248166269' where id='washington-square';
insert into public.places (id,name,kind,address,description,visit_note,source_url,neighborhood,latitude,longitude,coordinate_source_url,verified_on) values
('joe-waverly','Joe Coffee · Waverly Place','coffee','141 Waverly Place, New York, NY 10014','The original Joe Coffee cafe on a Village corner.','Check the source for current hours, menu and seating; no purchase is required to follow the walk.','https://joecoffeecompany.com/pages/west-village','West Village',40.7333179,-74.0005572,'https://www.openstreetmap.org/node/2358048509','2026-10-08'),
('elk-village','The ELK · West Village','coffee','128 Charles Street, New York, NY 10014','A neighborhood coffee shop on Charles Street.','Check the source for current hours, menu and seating; no purchase is required to follow the walk.','https://www.theelknyc.com/','West Village',40.7341801,-74.0074243,'https://www.openstreetmap.org/node/2567575076','2026-10-08'),
('abingdon-square','Abingdon Square','park','Hudson Street, Eighth Avenue and West 12th Street, New York, NY','A small historic public square with seasonal planting.','Free public outdoor stop. Check current access and park notices; paths or stairs may affect accessibility.','https://www.nycgovparks.org/parks/abingdon-square','West Village',40.7373183,-74.0054416,'https://www.openstreetmap.org/way/86144190','2026-10-08'),
('jackson-square','Jackson Square','park','Greenwich Avenue, Eighth Avenue and Horatio Street, New York, NY','A triangular public park at the edge of the Village.','Free public outdoor stop. Check current access and park notices; paths or stairs may affect accessibility.','https://www.nycgovparks.org/parks/jackson-square','West Village',40.7390068,-74.0028275,'https://www.openstreetmap.org/way/22961817','2026-10-08'),
('three-lives','Three Lives & Company','bookshop','154 West 10th Street, New York, NY 10014','An independent neighborhood bookstore.','Browse respectfully during store hours. Purchases are optional; check the source before visiting.','https://www.threelives.com/','West Village',40.7343633,-74.0015255,'https://www.openstreetmap.org/node/11120945208','2026-10-08'),
('colombe-lafayette','La Colombe · Lafayette Street','coffee','270 Lafayette Street, New York, NY 10012','A coffee starting point near Prince Street.','Check the source for current hours, menu and seating; no purchase is required to follow the walk.','https://www.lacolombe.com/pages/cafes/soho','SoHo / Nolita',40.7239788,-73.9964591,'https://www.openstreetmap.org/node/2547241611','2026-10-08'),
('colombe-prince','La Colombe · Prince Street','coffee','154 Prince Street, New York, NY 10012','A coffee stop near SoHo''s cast-iron streetscapes.','Check the source for current hours, menu and seating; no purchase is required to follow the walk.','https://www.lacolombe.com/pages/cafes','SoHo / Nolita',40.7257887,-74.0011724,'https://www.openstreetmap.org/node/5796438080','2026-10-08'),
('housing-works','Housing Works Bookstore & Cafe','coffee','126 Crosby Street, New York, NY 10012','A used bookstore and cafe supporting Housing Works; browse books with your coffee.','Check the source for current hours, menu and seating; no purchase is required to follow the walk.','https://shop.housingworks.org/nyc-bookstore/','SoHo / Nolita',40.7245873,-73.9964985,'https://www.openstreetmap.org/node/2501562611','2026-10-08'),
('mcnally-prince','McNally Jackson · Prince Street','bookshop','134 Prince Street, New York, NY 10012','An independent bookstore in SoHo.','Browse respectfully during store hours. Purchases are optional; check the source before visiting.','https://mcnallyjackson.com/find-our-stores','SoHo / Nolita',40.7254909,-74.0005101,'https://www.openstreetmap.org/node/2547223606','2026-10-08'),
('petrosino-square','Petrosino Square','park','Lafayette Street and Kenmare Street, New York, NY','A small public square where SoHo and Nolita meet.','Free public outdoor stop. Check current access and park notices; paths or stairs may affect accessibility.','https://www.nycgovparks.org/parks/petrosino-square','SoHo / Nolita',40.7217778,-73.9974462,'https://www.openstreetmap.org/way/44225581','2026-10-08'),
('old-st-patricks','Old St. Patrick''s Cathedral · Exterior','landmark','263 Mulberry Street, New York, NY 10012','A historic cathedral facade to view from the public street.','This route uses an exterior view from public space. Indoor visits, tours or grounds may have separate access rules or fees.','https://oldcathedral.org/','SoHo / Nolita',40.7235812,-73.9951929,'https://www.openstreetmap.org/way/247845702','2026-10-08'),
('earth-room','The New York Earth Room','gallery','141 Wooster Street, New York, NY 10012','Walter De Maria''s long-term earth installation, maintained by Dia.','Free admission; Wednesday–Sunday from noon, with an afternoon break and holiday closures. Check Dia for access and current hours.','https://www.diaart.org/visit/visit-our-locations-sites/walter-de-maria-the-new-york-earth-room-new-york-united-states','SoHo / Nolita',40.7259792,-73.9997541,'https://www.openstreetmap.org/node/9470799318','2026-10-08'),
('hungarian-pastry','The Hungarian Pastry Shop','coffee','1030 Amsterdam Avenue, New York, NY 10025','A longstanding cafe across from St. John the Divine, popular with readers and writers.','Check the source for current hours, menu and seating; no purchase is required to follow the walk.','https://www.hungarianpastryshop.com/','Columbia / Upper West Side',40.803562,-73.9636828,'https://www.openstreetmap.org/node/2827478159','2026-10-08'),
('plowshares-broadway','Plowshares Coffee · Broadway','coffee','2730 Broadway, New York, NY 10025','An independent coffee roaster''s cafe between West 104th and 105th Streets.','Check the source for current hours, menu and seating; no purchase is required to follow the walk.','https://www.plowsharescoffee.com/plowshares-coffee-cafe/','Columbia / Upper West Side',40.8001351,-73.9677641,'https://www.openstreetmap.org/node/4850904724','2026-10-08'),
('book-culture-112','Book Culture · 112th Street','bookshop','536 West 112th Street, New York, NY 10025','An independent bookstore near Columbia.','Browse respectfully during store hours. Purchases are optional; check the source before visiting.','https://bookculture.com/locations','Columbia / Upper West Side',40.8050208,-73.9650084,'https://www.openstreetmap.org/node/2707989850','2026-10-08'),
('morningside-park','Morningside Park','park','Morningside Park, Manhattan, New York, NY','A public park along the eastern edge of Morningside Heights.','Free public outdoor stop. Check current access and park notices; paths or stairs may affect accessibility.','https://www.nycgovparks.org/parks/morningside-park','Columbia / Upper West Side',40.8060208,-73.9587048,'https://www.openstreetmap.org/way/39243853','2026-10-08'),
('sakura-park','Sakura Park','park','Riverside Drive and West 122nd Street, New York, NY','A quiet public park beside Riverside Church.','Free public outdoor stop. Check current access and park notices; paths or stairs may affect accessibility.','https://www.nycgovparks.org/parks/sakura-park','Columbia / Upper West Side',40.8129879,-73.9621515,'https://www.openstreetmap.org/way/118528233','2026-10-08'),
('grant-tomb','General Grant National Memorial','landmark','Riverside Drive and West 122nd Street, New York, NY','A monumental memorial near the Hudson; explore the exterior plaza.','This route uses an exterior view from public space. Indoor visits, tours or grounds may have separate access rules or fees.','https://www.nps.gov/gegr/planyourvisit/directions.htm','Columbia / Upper West Side',40.8134538,-73.9630506,'https://www.openstreetmap.org/way/271922197','2026-10-08'),
('st-john-divine','St. John the Divine · Exterior','landmark','1047 Amsterdam Avenue, New York, NY 10025','A cathedral facade and architectural stop across from the Hungarian Pastry Shop.','This route uses an exterior view from public space. Indoor visits, tours or grounds may have separate access rules or fees.','https://www.stjohndivine.org/','Columbia / Upper West Side',40.803766,-73.9617843,'https://www.openstreetmap.org/relation/3624833','2026-10-08'),
('riverside-church','Riverside Church · Exterior','landmark','490 Riverside Drive, New York, NY 10027','A landmark tower and church exterior near Sakura Park.','This route uses an exterior view from public space. Indoor visits, tours or grounds may have separate access rules or fees.','https://www.trcnyc.org/','Columbia / Upper West Side',40.8120673,-73.9630134,'https://www.openstreetmap.org/way/274986253','2026-10-08')
on conflict (id) do update set name=excluded.name,kind=excluded.kind,address=excluded.address,description=excluded.description,visit_note=excluded.visit_note,source_url=excluded.source_url,neighborhood=excluded.neighborhood,latitude=excluded.latitude,longitude=excluded.longitude,coordinate_source_url=excluded.coordinate_source_url,verified_on=excluded.verified_on;
-- The existing RLS and read-only catalogue grants stay in force.
commit;
select neighborhood,count(*) as places,count(*) filter (where kind='coffee') as coffee_starts from public.places group by neighborhood order by neighborhood;
